services:
  # -----------------------------------------
  # BASE DE DATOS - MYSQL
  # -----------------------------------------
  database:
    image: mysql:8
    container_name: adj-database
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: adj-demo
    ports:
      - "3307:3306"
    volumes:
      - adj-volume:/var/lib/mysql
    networks:
      - adj-net

  # -----------------------------------------
  # BACKEND — SPRING BOOT
  # -----------------------------------------
  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: adj-server
    image: adj-server:latest
    environment:
      SERVER_PORT: 8080
      DB_HOST: database
      DB_PORT: 3306
      DB_NAME: adj-demo
      DB_USER: root
      DB_PASS: root
    ports:
      - "8081:8080"
    depends_on:
      - database
    networks:
      - adj-net

  # -----------------------------------------
  # FRONTEND — REACT VITE + NGINX
  # -----------------------------------------
  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
      args:
        API_HOST: localhost
        API_PORT: 8081
        API_BASE: /adj-api
    container_name: adj-client
    image: adj-client:latest
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - adj-net

volumes:
  adj-volume:
    external: true

networks:
  adj-net:
    external: true
